export const data = [
  {
    no: 1,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Waiting for approval",
    rejectionReason: "",
    approvalDateTime: "",
  },
  {
    no: 2,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approval denied",
    rejectionReason:
      "Documents cannot be identified. Professional investors cannot be approved as the account was opened at a financial investment company less than 1 year ago.",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 3,
    existingType: "Income eligibilty",
    applicationType: "Income eligibilty",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approved",
    rejectionReason: "",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 4,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Waiting for approval",
    rejectionReason: "",
    approvalDateTime: "",
  },
  {
    no: 5,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approval denied",
    rejectionReason:
      "Documents cannot be identified. Professional investors cannot be approved as the account was opened at a financial investment company less than 1 year ago.",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 6,
    existingType: "General Individual",
    applicationType: "Income eligibility",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approved",
    rejectionReason: "",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 7,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Waiting for approval",
    rejectionReason: "",
    approvalDateTime: "",
  },
  {
    no: 8,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approval denied",
    rejectionReason:
      "Documents cannot be identified. Professional investors cannot be approved as the account was opened at a financial investment company less than 1 year ago.",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 9,
    existingType: "General individual",
    applicationType: "Income eligibility",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approved",
    rejectionReason: "",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 10,
    existingType: "Income eligibility",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Waiting for approval",
    rejectionReason: "",
    approvalDateTime: "",
  },
  {
    no: 11,
    existingType: "Income eligibility",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approval denied",
    rejectionReason:
      "Documents cannot be identified. Professional investors cannot be approved as the account was opened at a financial investment company less than 1 year ago.",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 12,
    existingType: "General individual",
    applicationType: "Income eligibility",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approved",
    rejectionReason: "",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 13,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Waiting for approval",
    rejectionReason: "",
    approvalDateTime: "",
  },
  {
    no: 14,
    existingType: "Income eligibility",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approval denied",
    rejectionReason:
      "Documents cannot be identified. Professional investors cannot be approved as the account was opened at a financial investment company less than 1 year ago.",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 15,
    existingType: "General individual",
    applicationType: "Income eligibility",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approved",
    rejectionReason: "",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 16,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Waiting for approval",
    rejectionReason: "",
    approvalDateTime: "",
  },
  {
    no: 17,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approval denied",
    rejectionReason:
      "Documents cannot be identified. Professional investors cannot be approved as the account was opened at a financial investment company less than 1 year ago.",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 18,
    existingType: "General individual",
    applicationType: "Income eligibility",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approved",
    rejectionReason: "",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 19,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Waiting for approval",
    rejectionReason: "",
    approvalDateTime: "",
  },
  {
    no: 20,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approval denied",
    rejectionReason:
      "Documents cannot be identified. Professional investors cannot be approved as the account was opened at a financial investment company less than 1 year ago.",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 21,
    existingType: "General individual",
    applicationType: "Income eligibility",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approved",
    rejectionReason: "",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 22,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Waiting for approval",
    rejectionReason: "",
    approvalDateTime: "",
  },
  {
    no: 23,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approval denied",
    rejectionReason:
      "Documents cannot be identified. Professional investors cannot be approved as the account was opened at a financial investment company less than 1 year ago.",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 24,
    existingType: "General individual",
    applicationType: "Income eligibility",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approved",
    rejectionReason: "",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 25,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Waiting for approval",
    rejectionReason: "",
    approvalDateTime: "",
  },
  {
    no: 26,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approval denied",
    rejectionReason:
      "Documents cannot be identified. Professional investors cannot be approved as the account was opened at a financial investment company less than 1 year ago.",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 27,
    existingType: "General individual",
    applicationType: "Income eligibility",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approved",
    rejectionReason: "",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 28,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Waiting for approval",
    rejectionReason: "",
    approvalDateTime: "",
  },
  {
    no: 29,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approval denied",
    rejectionReason:
      "Documents cannot be identified. Professional investors cannot be approved as the account was opened at a financial investment company less than 1 year ago.",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 30,
    existingType: "General individual",
    applicationType: "Income eligibility",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approved",
    rejectionReason: "",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 31,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Waiting for approval",
    rejectionReason: "",
    approvalDateTime: "",
  },
  {
    no: 32,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approval denied",
    rejectionReason:
      "Documents cannot be identified. Professional investors cannot be approved as the account was opened at a financial investment company less than 1 year ago.",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 33,
    existingType: "General individual",
    applicationType: "Income eligibility",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approved",
    rejectionReason: "",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 34,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Waiting for approval",
    rejectionReason: "",
    approvalDateTime: "",
  },
  {
    no: 35,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approval denied",
    rejectionReason:
      "Documents cannot be identified. Professional investors cannot be approved as the account was opened at a financial investment company less than 1 year ago.",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 36,
    existingType: "General individual",
    applicationType: "Income eligibility",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approved",
    rejectionReason: "",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 37,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Waiting for approval",
    rejectionReason: "",
    approvalDateTime: "",
  },
  {
    no: 38,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approval denied",
    rejectionReason:
      "Documents cannot be identified. Professional investors cannot be approved as the account was opened at a financial investment company less than 1 year ago.",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 39,
    existingType: "General individual",
    applicationType: "Income eligibility",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approved",
    rejectionReason: "",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 40,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Waiting for approval",
    rejectionReason: "",
    approvalDateTime: "",
  },
  {
    no: 41,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approval denied",
    rejectionReason:
      "Documents cannot be identified. Professional investors cannot be approved as the account was opened at a financial investment company less than 1 year ago.",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 42,
    existingType: "General individual",
    applicationType: "Income eligibility",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approved",
    rejectionReason: "",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 43,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Waiting for approval",
    rejectionReason: "",
    approvalDateTime: "",
  },
  {
    no: 44,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approval denied",
    rejectionReason:
      "Documents cannot be identified. Professional investors cannot be approved as the account was opened at a financial investment company less than 1 year ago.",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 45,
    existingType: "General individual",
    applicationType: "Income eligibility",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approved",
    rejectionReason: "",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 46,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Waiting for approval",
    rejectionReason: "",
    approvalDateTime: "",
  },
  {
    no: 47,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approval denied",
    rejectionReason:
      "Documents cannot be identified. Professional investors cannot be approved as the account was opened at a financial investment company less than 1 year ago.",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 48,
    existingType: "General individual",
    applicationType: "Income eligibility",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approved",
    rejectionReason: "",
    approvalDateTime: "2023-01-10 09:00:00",
  },
  {
    no: 49,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Waiting for approval",
    rejectionReason: "",
    approvalDateTime: "",
  },
  {
    no: 50,
    existingType: "Income eligibilty",
    applicationType: "Personal expertise",
    documents: "view",
    applicationDateTime: "2023-01-10 09:00:00",
    approval: "Approval denied",
    rejectionReason:
      "Documents cannot be identified. Professional investors cannot be approved as the account was opened at a financial investment company less than 1 year ago.",
    approvalDateTime: "2023-01-10 09:00:00",
  },
];
